import type { LegoCatalogSnapshot, LegoDependencySuggestion, LegoLanguage } from './types';

/* Versioned server-only catalogue data. SQLite is the runtime authority. */
export type SeedHostingMode = 'client' | 'baas' | 'cloud' | 'selfhosted';
export interface SeedIntent { id: string; label: string; modes: readonly SeedHostingMode[]; shapes?: readonly string[]; }
export interface SeedVariant { id: string; intent: string; label: string; mode: SeedHostingMode; maps_to: string; }

const INTENTS: readonly SeedIntent[] = [
  { id: 'web-app', label: 'Web app', modes: ['client'] },
  { id: 'mobile-app', label: 'Mobile app', modes: ['client'] },
  { id: 'auth', label: 'Auth', modes: ['baas', 'cloud', 'selfhosted'] },
  { id: 'api', label: 'API', modes: ['cloud', 'selfhosted'], shapes: ['gateway', 'compute'] },
  { id: 'cdn', label: 'CDN / static', modes: ['cloud', 'selfhosted'], shapes: ['cdn', 'static'] },
  { id: 'workers', label: 'Workers / jobs', modes: ['cloud', 'selfhosted'], shapes: ['worker', 'schedule', 'workflow'] },
  { id: 'database', label: 'Database / cache', modes: ['baas', 'cloud', 'selfhosted'], shapes: ['sql', 'nosql', 'cache'] },
  { id: 'files', label: 'Files / objects', modes: ['baas', 'cloud', 'selfhosted'] },
  { id: 'search', label: 'Search', modes: ['baas', 'cloud', 'selfhosted'], shapes: ['fulltext', 'vector'] },
  { id: 'messaging', label: 'Messaging', modes: ['baas', 'cloud', 'selfhosted'], shapes: ['queue', 'bus', 'stream'] },
  { id: 'llm', label: 'LLM / AI', modes: ['baas', 'cloud', 'selfhosted'] },
  { id: 'ops', label: 'Ops', modes: ['baas', 'cloud', 'selfhosted'], shapes: ['observe', 'ship', 'mail'] }
];

const VARIANTS: readonly SeedVariant[] = [
  { id: 'nextjs', intent: 'web-app', label: 'Next.js', mode: 'client', maps_to: 'webApp' },
  { id: 'remix', intent: 'web-app', label: 'Remix', mode: 'client', maps_to: 'webApp' },
  { id: 'nuxt', intent: 'web-app', label: 'Nuxt', mode: 'client', maps_to: 'webApp' },
  { id: 'sveltekit', intent: 'web-app', label: 'SvelteKit', mode: 'client', maps_to: 'webApp' },
  { id: 'spa-react', intent: 'web-app', label: 'SPA — React', mode: 'client', maps_to: 'webApp' },
  { id: 'spa-vue', intent: 'web-app', label: 'SPA — Vue', mode: 'client', maps_to: 'webApp' },
  { id: 'spa-svelte', intent: 'web-app', label: 'SPA — Svelte', mode: 'client', maps_to: 'webApp' },
  { id: 'spa-angular', intent: 'web-app', label: 'SPA — Angular', mode: 'client', maps_to: 'webApp' },
  { id: 'astro', intent: 'web-app', label: 'Astro', mode: 'client', maps_to: 'webApp' },
  { id: 'admin-next', intent: 'web-app', label: 'Admin — Next.js', mode: 'client', maps_to: 'webApp' },
  { id: 'admin-spa-react', intent: 'web-app', label: 'Admin — React SPA', mode: 'client', maps_to: 'webApp' },
  { id: 'react-native', intent: 'mobile-app', label: 'React Native', mode: 'client', maps_to: 'mobileApp' },
  { id: 'flutter', intent: 'mobile-app', label: 'Flutter', mode: 'client', maps_to: 'mobileApp' },
  { id: 'swift-ios', intent: 'mobile-app', label: 'Native Swift (iOS)', mode: 'client', maps_to: 'mobileApp' },
  { id: 'kotlin-android', intent: 'mobile-app', label: 'Native Kotlin (Android)', mode: 'client', maps_to: 'mobileApp' },
  { id: 'expo', intent: 'mobile-app', label: 'Expo (React Native)', mode: 'client', maps_to: 'mobileApp' },
  { id: 'capacitor', intent: 'mobile-app', label: 'Capacitor', mode: 'client', maps_to: 'mobileApp' },
  { id: 'kotlin-multiplatform', intent: 'mobile-app', label: 'Kotlin Multiplatform', mode: 'client', maps_to: 'mobileApp' },
  { id: 'firebase-auth', intent: 'auth', label: 'Firebase Auth', mode: 'baas', maps_to: 'identity' },
  { id: 'supabase-auth', intent: 'auth', label: 'Supabase Auth', mode: 'baas', maps_to: 'identity' },
  { id: 'appwrite-auth', intent: 'auth', label: 'Appwrite Auth', mode: 'baas', maps_to: 'identity' },
  { id: 'clerk', intent: 'auth', label: 'Clerk', mode: 'baas', maps_to: 'identity' },
  { id: 'auth0', intent: 'auth', label: 'Auth0', mode: 'cloud', maps_to: 'identity' },
  { id: 'workos', intent: 'auth', label: 'WorkOS', mode: 'cloud', maps_to: 'identity' },
  { id: 'cognito', intent: 'auth', label: 'Amazon Cognito', mode: 'cloud', maps_to: 'identity' },
  { id: 'identity-platform', intent: 'auth', label: 'Google Identity Platform', mode: 'cloud', maps_to: 'identity' },
  { id: 'entra-external-id', intent: 'auth', label: 'Microsoft Entra External ID', mode: 'cloud', maps_to: 'identity' },
  { id: 'keycloak', intent: 'auth', label: 'Keycloak', mode: 'selfhosted', maps_to: 'identity' },
  { id: 'zitadel', intent: 'auth', label: 'Zitadel', mode: 'selfhosted', maps_to: 'identity' },
  { id: 'ory-kratos', intent: 'auth', label: 'Ory Kratos', mode: 'selfhosted', maps_to: 'identity' },
  { id: 'authentik', intent: 'auth', label: 'Authentik', mode: 'selfhosted', maps_to: 'identity' },
  { id: 'supabase-auth-selfhost', intent: 'auth', label: 'Supabase Auth (self-host)', mode: 'selfhosted', maps_to: 'identity' },
  { id: 'aws-api-gateway', intent: 'api', label: 'Amazon API Gateway', mode: 'cloud', maps_to: 'apiGateway' },
  { id: 'gcp-api-gateway', intent: 'api', label: 'Google API Gateway', mode: 'cloud', maps_to: 'apiGateway' },
  { id: 'azure-apim', intent: 'api', label: 'Azure API Management', mode: 'cloud', maps_to: 'apiGateway' },
  { id: 'traefik', intent: 'api', label: 'Traefik', mode: 'selfhosted', maps_to: 'apiGateway' },
  { id: 'kong', intent: 'api', label: 'Kong', mode: 'selfhosted', maps_to: 'apiGateway' },
  { id: 'nginx-gateway', intent: 'api', label: 'Nginx / Ingress', mode: 'selfhosted', maps_to: 'apiGateway' },
  { id: 'aws-lambda', intent: 'api', label: 'AWS Lambda', mode: 'cloud', maps_to: 'functions' },
  { id: 'gcp-cloud-run-functions', intent: 'api', label: 'Cloud Run functions', mode: 'cloud', maps_to: 'functions' },
  { id: 'azure-functions', intent: 'api', label: 'Azure Functions', mode: 'cloud', maps_to: 'functions' },
  { id: 'aws-ecs-fargate', intent: 'api', label: 'ECS Fargate', mode: 'cloud', maps_to: 'containers' },
  { id: 'gcp-cloud-run', intent: 'api', label: 'Cloud Run', mode: 'cloud', maps_to: 'containers' },
  { id: 'azure-container-apps', intent: 'api', label: 'Azure Container Apps', mode: 'cloud', maps_to: 'containers' },
  { id: 'aws-eks', intent: 'api', label: 'Amazon EKS', mode: 'cloud', maps_to: 'kubernetes' },
  { id: 'gcp-gke', intent: 'api', label: 'GKE Autopilot', mode: 'cloud', maps_to: 'kubernetes' },
  { id: 'azure-aks', intent: 'api', label: 'Azure Kubernetes Service', mode: 'cloud', maps_to: 'kubernetes' },
  { id: 'openfaas-knative', intent: 'api', label: 'OpenFaaS / Knative', mode: 'selfhosted', maps_to: 'functions' },
  { id: 'docker-compose', intent: 'api', label: 'Docker Compose / Nomad', mode: 'selfhosted', maps_to: 'containers' },
  { id: 'k3s-talos', intent: 'api', label: 'k3s / Talos', mode: 'selfhosted', maps_to: 'kubernetes' },
  { id: 'cloudfront', intent: 'cdn', label: 'Amazon CloudFront', mode: 'cloud', maps_to: 'cdn' },
  { id: 'cloud-cdn', intent: 'cdn', label: 'Google Cloud CDN', mode: 'cloud', maps_to: 'cdn' },
  { id: 'front-door', intent: 'cdn', label: 'Azure Front Door', mode: 'cloud', maps_to: 'cdn' },
  { id: 's3-cloudfront-static', intent: 'cdn', label: 'S3 + CloudFront (static)', mode: 'cloud', maps_to: 'staticHosting' },
  { id: 'firebase-hosting', intent: 'cdn', label: 'Firebase Hosting', mode: 'cloud', maps_to: 'staticHosting' },
  { id: 'azure-static-web-apps', intent: 'cdn', label: 'Azure Static Web Apps', mode: 'cloud', maps_to: 'staticHosting' },
  { id: 'cloudflare-cdn', intent: 'cdn', label: 'Cloudflare CDN', mode: 'cloud', maps_to: 'cdn' },
  { id: 'nginx-varnish', intent: 'cdn', label: 'Nginx / Varnish', mode: 'selfhosted', maps_to: 'cdn' },
  { id: 'caddy-nginx-static', intent: 'cdn', label: 'Caddy / Nginx static', mode: 'selfhosted', maps_to: 'staticHosting' },
  { id: 'lambda-worker', intent: 'workers', label: 'Lambda (async / queue consumer)', mode: 'cloud', maps_to: 'functions' },
  { id: 'cloud-run-jobs', intent: 'workers', label: 'Cloud Run Jobs', mode: 'cloud', maps_to: 'jobs' },
  { id: 'azure-container-apps-jobs', intent: 'workers', label: 'Container Apps Jobs', mode: 'cloud', maps_to: 'jobs' },
  { id: 'ecs-scheduled', intent: 'workers', label: 'ECS scheduled tasks', mode: 'cloud', maps_to: 'jobs' },
  { id: 'gcp-cloud-scheduler', intent: 'workers', label: 'Cloud Scheduler + Jobs', mode: 'cloud', maps_to: 'jobs' },
  { id: 'eventbridge-scheduler', intent: 'workers', label: 'EventBridge Scheduler', mode: 'cloud', maps_to: 'jobs' },
  { id: 'step-functions', intent: 'workers', label: 'AWS Step Functions', mode: 'cloud', maps_to: 'orchestration' },
  { id: 'gcp-workflows', intent: 'workers', label: 'Google Workflows', mode: 'cloud', maps_to: 'orchestration' },
  { id: 'durable-functions', intent: 'workers', label: 'Azure Durable Functions', mode: 'cloud', maps_to: 'orchestration' },
  { id: 'temporal', intent: 'workers', label: 'Temporal', mode: 'selfhosted', maps_to: 'orchestration' },
  { id: 'k8s-cronjob', intent: 'workers', label: 'Kubernetes CronJob', mode: 'selfhosted', maps_to: 'jobs' },
  { id: 'systemd-nomad', intent: 'workers', label: 'systemd / Nomad periodic', mode: 'selfhosted', maps_to: 'jobs' },
  { id: 'docker-worker', intent: 'workers', label: 'Docker Compose worker', mode: 'selfhosted', maps_to: 'containers' },
  { id: 'supabase-postgres', intent: 'database', label: 'Supabase (Postgres)', mode: 'baas', maps_to: 'sql' },
  { id: 'neon', intent: 'database', label: 'Neon', mode: 'baas', maps_to: 'sql' },
  { id: 'planetscale', intent: 'database', label: 'PlanetScale', mode: 'baas', maps_to: 'sql' },
  { id: 'firebase-firestore', intent: 'database', label: 'Cloud Firestore', mode: 'baas', maps_to: 'nosql' },
  { id: 'aurora-postgres', intent: 'database', label: 'Amazon Aurora PostgreSQL', mode: 'cloud', maps_to: 'sql' },
  { id: 'cloud-sql', intent: 'database', label: 'Cloud SQL / AlloyDB', mode: 'cloud', maps_to: 'sql' },
  { id: 'azure-postgres', intent: 'database', label: 'Azure Database for PostgreSQL', mode: 'cloud', maps_to: 'sql' },
  { id: 'postgres-patroni', intent: 'database', label: 'PostgreSQL (Patroni)', mode: 'selfhosted', maps_to: 'sql' },
  { id: 'dynamodb', intent: 'database', label: 'Amazon DynamoDB', mode: 'cloud', maps_to: 'nosql' },
  { id: 'firestore', intent: 'database', label: 'Firestore', mode: 'cloud', maps_to: 'nosql' },
  { id: 'cosmosdb', intent: 'database', label: 'Azure Cosmos DB', mode: 'cloud', maps_to: 'nosql' },
  { id: 'mongodb', intent: 'database', label: 'MongoDB', mode: 'selfhosted', maps_to: 'nosql' },
  { id: 'mongodb-atlas', intent: 'database', label: 'MongoDB Atlas', mode: 'baas', maps_to: 'nosql' },
  { id: 'elasticache', intent: 'database', label: 'Amazon ElastiCache', mode: 'cloud', maps_to: 'cache' },
  { id: 'memorystore', intent: 'database', label: 'Memorystore', mode: 'cloud', maps_to: 'cache' },
  { id: 'azure-managed-redis', intent: 'database', label: 'Azure Managed Redis', mode: 'cloud', maps_to: 'cache' },
  { id: 'upstash-redis', intent: 'database', label: 'Upstash Redis', mode: 'baas', maps_to: 'cache' },
  { id: 'valkey', intent: 'database', label: 'Valkey / Redis', mode: 'selfhosted', maps_to: 'cache' },
  { id: 's3', intent: 'files', label: 'Amazon S3', mode: 'cloud', maps_to: 'objects' },
  { id: 'gcs', intent: 'files', label: 'Google Cloud Storage', mode: 'cloud', maps_to: 'objects' },
  { id: 'azure-blob', intent: 'files', label: 'Azure Blob Storage', mode: 'cloud', maps_to: 'objects' },
  { id: 'supabase-storage', intent: 'files', label: 'Supabase Storage', mode: 'baas', maps_to: 'objects' },
  { id: 'firebase-storage', intent: 'files', label: 'Firebase Storage', mode: 'baas', maps_to: 'objects' },
  { id: 'cloudflare-r2', intent: 'files', label: 'Cloudflare R2', mode: 'cloud', maps_to: 'objects' },
  { id: 'minio', intent: 'files', label: 'MinIO', mode: 'selfhosted', maps_to: 'objects' },
  { id: 'opensearch-aws', intent: 'search', label: 'Amazon OpenSearch Service', mode: 'cloud', maps_to: 'search' },
  { id: 'elastic-cloud', intent: 'search', label: 'Elastic Cloud', mode: 'cloud', maps_to: 'search' },
  { id: 'azure-ai-search', intent: 'search', label: 'Azure AI Search', mode: 'cloud', maps_to: 'search' },
  { id: 'algolia', intent: 'search', label: 'Algolia', mode: 'baas', maps_to: 'search' },
  { id: 'typesense-cloud', intent: 'search', label: 'Typesense Cloud', mode: 'baas', maps_to: 'search' },
  { id: 'opensearch-self', intent: 'search', label: 'OpenSearch', mode: 'selfhosted', maps_to: 'search' },
  { id: 'meilisearch', intent: 'search', label: 'Meilisearch', mode: 'selfhosted', maps_to: 'search' },
  { id: 'qdrant', intent: 'search', label: 'Qdrant', mode: 'selfhosted', maps_to: 'vector' },
  { id: 'pgvector', intent: 'search', label: 'pgvector', mode: 'selfhosted', maps_to: 'vector' },
  { id: 'vertex-vector', intent: 'search', label: 'Vertex / Agent Platform Vector Search', mode: 'cloud', maps_to: 'vector' },
  { id: 'opensearch-vector-aws', intent: 'search', label: 'OpenSearch vector engine', mode: 'cloud', maps_to: 'vector' },
  { id: 'sqs', intent: 'messaging', label: 'Amazon SQS', mode: 'cloud', maps_to: 'queue' },
  { id: 'pubsub-pull', intent: 'messaging', label: 'Cloud Pub/Sub (pull)', mode: 'cloud', maps_to: 'queue' },
  { id: 'service-bus', intent: 'messaging', label: 'Azure Service Bus', mode: 'cloud', maps_to: 'queue' },
  { id: 'rabbitmq', intent: 'messaging', label: 'RabbitMQ', mode: 'selfhosted', maps_to: 'queue' },
  { id: 'nats-jetstream', intent: 'messaging', label: 'NATS JetStream', mode: 'selfhosted', maps_to: 'queue' },
  { id: 'eventbridge', intent: 'messaging', label: 'Amazon EventBridge', mode: 'cloud', maps_to: 'pubsub' },
  { id: 'pubsub', intent: 'messaging', label: 'Cloud Pub/Sub', mode: 'cloud', maps_to: 'pubsub' },
  { id: 'event-grid', intent: 'messaging', label: 'Azure Event Grid', mode: 'cloud', maps_to: 'pubsub' },
  { id: 'supabase-realtime', intent: 'messaging', label: 'Supabase Realtime', mode: 'baas', maps_to: 'pubsub' },
  { id: 'firebase-pubsub', intent: 'messaging', label: 'Firebase / FCM-style fan-out', mode: 'baas', maps_to: 'pubsub' },
  { id: 'kinesis', intent: 'messaging', label: 'Amazon Kinesis Data Streams', mode: 'cloud', maps_to: 'stream' },
  { id: 'msk', intent: 'messaging', label: 'Amazon MSK', mode: 'cloud', maps_to: 'stream' },
  { id: 'event-hubs', intent: 'messaging', label: 'Azure Event Hubs', mode: 'cloud', maps_to: 'stream' },
  { id: 'kafka', intent: 'messaging', label: 'Apache Kafka', mode: 'selfhosted', maps_to: 'stream' },
  { id: 'redpanda', intent: 'messaging', label: 'Redpanda', mode: 'selfhosted', maps_to: 'stream' },
  { id: 'openai', intent: 'llm', label: 'OpenAI API', mode: 'baas', maps_to: 'llm' },
  { id: 'anthropic', intent: 'llm', label: 'Anthropic API', mode: 'baas', maps_to: 'llm' },
  { id: 'bedrock', intent: 'llm', label: 'Amazon Bedrock', mode: 'cloud', maps_to: 'llm' },
  { id: 'agent-platform', intent: 'llm', label: 'Gemini Enterprise Agent Platform', mode: 'cloud', maps_to: 'llm' },
  { id: 'foundry', intent: 'llm', label: 'Microsoft Foundry', mode: 'cloud', maps_to: 'llm' },
  { id: 'groq', intent: 'llm', label: 'Groq', mode: 'baas', maps_to: 'llm' },
  { id: 'mistral-api', intent: 'llm', label: 'Mistral API', mode: 'baas', maps_to: 'llm' },
  { id: 'vllm', intent: 'llm', label: 'vLLM', mode: 'selfhosted', maps_to: 'llm' },
  { id: 'ollama', intent: 'llm', label: 'Ollama', mode: 'selfhosted', maps_to: 'llm' },
  { id: 'tgi', intent: 'llm', label: 'Text Generation Inference', mode: 'selfhosted', maps_to: 'llm' },
  { id: 'cloudwatch', intent: 'ops', label: 'Amazon CloudWatch', mode: 'cloud', maps_to: 'observability' },
  { id: 'gcp-ops', intent: 'ops', label: 'Cloud Logging & Monitoring', mode: 'cloud', maps_to: 'observability' },
  { id: 'app-insights', intent: 'ops', label: 'Application Insights', mode: 'cloud', maps_to: 'observability' },
  { id: 'xray', intent: 'ops', label: 'AWS X-Ray', mode: 'cloud', maps_to: 'tracing' },
  { id: 'cloud-trace', intent: 'ops', label: 'Cloud Trace', mode: 'cloud', maps_to: 'tracing' },
  { id: 'grafana-stack', intent: 'ops', label: 'Prometheus + Grafana + Loki', mode: 'selfhosted', maps_to: 'observability' },
  { id: 'tempo-jaeger', intent: 'ops', label: 'Tempo / Jaeger', mode: 'selfhosted', maps_to: 'tracing' },
  { id: 'datadog', intent: 'ops', label: 'Datadog', mode: 'baas', maps_to: 'observability' },
  { id: 'sentry', intent: 'ops', label: 'Sentry', mode: 'baas', maps_to: 'observability' },
  { id: 'github-actions-aws', intent: 'ops', label: 'GitHub Actions + AWS CDK', mode: 'cloud', maps_to: 'cicd' },
  { id: 'cloud-build', intent: 'ops', label: 'Cloud Build + Terraform', mode: 'cloud', maps_to: 'cicd' },
  { id: 'github-actions-bicep', intent: 'ops', label: 'GitHub Actions + Bicep', mode: 'cloud', maps_to: 'cicd' },
  { id: 'forgejo-ansible', intent: 'ops', label: 'Forgejo Actions + Ansible', mode: 'selfhosted', maps_to: 'cicd' },
  { id: 'argo-cd', intent: 'ops', label: 'Argo CD', mode: 'selfhosted', maps_to: 'gitops' },
  { id: 'github-actions-argo', intent: 'ops', label: 'GitHub Actions + Argo CD', mode: 'cloud', maps_to: 'gitops' },
  { id: 'ses', intent: 'ops', label: 'Amazon SES', mode: 'cloud', maps_to: 'email' },
  { id: 'sendgrid', intent: 'ops', label: 'SendGrid / Resend', mode: 'cloud', maps_to: 'email' },
  { id: 'acs-email', intent: 'ops', label: 'Azure Communication Services Email', mode: 'cloud', maps_to: 'email' },
  { id: 'postal', intent: 'ops', label: 'Postal / SMTP relay', mode: 'selfhosted', maps_to: 'email' },
  { id: 'postmark', intent: 'ops', label: 'Postmark', mode: 'baas', maps_to: 'email' },
  { id: 'resend', intent: 'ops', label: 'Resend', mode: 'baas', maps_to: 'email' },
] as const;

const LOCKED_SCOPES = [
  ['product', 'Product', 'Produit'],
  ['platform', 'Platform', 'Plateforme'],
  ['vendor', 'Third party', 'Tiers'],
  ['front', 'Front & console', 'Front & console'],
  ['app', 'Application', 'Application'],
  ['data', 'Data', 'Données'],
  ['tenancy', 'Tenancy & security', 'Tenancy & sécurité'],
  ['edge', 'Edge', 'Edge'],
  ['services', 'Business services', 'Services métier'],
  ['modules', 'Business modules', 'Modules métier'],
  ['ingestion', 'Ingestion', 'Ingestion'],
  ['index', 'Index & data', 'Index & données'],
  ['answering', 'Answering service', 'Service de réponse'],
  ['quality', 'Platform & quality', 'Plateforme & qualité'],
  ['producers', 'Producers', 'Producteurs'],
  ['bus', 'Bus & routing', 'Bus & routage'],
  ['processing', 'Processing', 'Traitement'],
  ['destinations', 'Destinations', 'Destinations']
] as const;

const SCOPE_ALIASES: Record<string, string> = {
  core: 'product',
  business: 'product',
  consumer: 'product'
};

const ROLE_SCOPES: Record<string, readonly string[]> = {
  webApp: ['front'],
  mobileApp: ['front'],
  staticHosting: ['front', 'edge'],
  cdn: ['edge'],
  apiGateway: ['edge', 'app', 'services'],
  waf: ['edge', 'tenancy'],
  loadBalancer: ['edge', 'app'],
  identity: ['tenancy', 'vendor'],
  functions: ['app', 'services', 'modules'],
  containers: ['app', 'services'],
  kubernetes: ['app', 'services', 'platform'],
  jobs: ['app', 'services', 'processing'],
  orchestration: ['app', 'services', 'ingestion'],
  sql: ['data', 'index'],
  nosql: ['data', 'index'],
  cache: ['data', 'quality'],
  objects: ['data', 'ingestion'],
  warehouse: ['data', 'index'],
  search: ['data', 'index'],
  vector: ['data', 'index'],
  queue: ['data', 'bus', 'processing'],
  pubsub: ['data', 'bus', 'producers'],
  stream: ['data', 'bus', 'processing'],
  streamProcessing: ['data', 'processing', 'destinations'],
  schemaRegistry: ['data', 'bus', 'quality'],
  embeddings: ['answering', 'index'],
  llm: ['answering'],
  rerank: ['answering', 'index'],
  guardrails: ['answering', 'quality'],
  ocr: ['ingestion', 'processing'],
  secrets: ['platform', 'tenancy'],
  config: ['platform', 'quality'],
  observability: ['platform', 'quality'],
  tracing: ['platform', 'quality'],
  backup: ['platform', 'data'],
  registry: ['platform'],
  cicd: ['platform'],
  gitops: ['platform'],
  audit: ['platform', 'quality'],
  email: ['vendor']
};

const ICONS: Record<string, string> = {
  webApp: 'web', mobileApp: 'mobile', apiGateway: 'plug', cdn: 'globe',
  waf: 'shield', loadBalancer: 'route',
  staticHosting: 'web', identity: 'lock', functions: 'bolt', containers: 'docker',
  kubernetes: 'layers', jobs: 'clock', orchestration: 'hub', sql: 'db', nosql: 'cube',
  cache: 'bolt', objects: 'save', warehouse: 'chart', search: 'search', vector: 'hub',
  queue: 'box', pubsub: 'bell', stream: 'chart', streamProcessing: 'cog',
  schemaRegistry: 'layers', embeddings: 'ai', llm: 'ai', rerank: 'layers',
  guardrails: 'shield', ocr: 'scan', secrets: 'key', config: 'flag',
  observability: 'chart', tracing: 'eye', backup: 'cloudup', registry: 'docker',
  email: 'mail', cicd: 'git', gitops: 'cloudup', audit: 'file'
};

const LAYERS: Record<string, string> = {
  webApp: 'clients', mobileApp: 'clients', cdn: 'edge', staticHosting: 'edge',
  apiGateway: 'edge', waf: 'edge', loadBalancer: 'edge', identity: 'edge',
  functions: 'services', containers: 'services', kubernetes: 'services',
  jobs: 'services', orchestration: 'services', streamProcessing: 'services',
  embeddings: 'services', llm: 'services', rerank: 'services', guardrails: 'services',
  ocr: 'services',
  sql: 'data', nosql: 'data', cache: 'data', objects: 'data', warehouse: 'data',
  search: 'data', vector: 'data', queue: 'data', pubsub: 'data', stream: 'data',
  schemaRegistry: 'data',
  secrets: 'platform', config: 'platform', observability: 'platform', tracing: 'platform',
  backup: 'platform', registry: 'platform', email: 'platform', cicd: 'platform',
  gitops: 'platform', audit: 'platform'
};

const SCOPES: Record<string, string> = {
  identity: 'vendor', email: 'vendor',
  secrets: 'platform', config: 'platform', observability: 'platform', tracing: 'platform',
  backup: 'platform', registry: 'platform', cicd: 'platform', gitops: 'platform', audit: 'platform'
};

const CAPABILITIES: Record<string, string[]> = {
  webApp: ['SPA'], mobileApp: ['SPA'], identity: ['OIDC', 'JWT', 'SAML', 'SCIM'],
  waf: ['WAF'], loadBalancer: ['TLS', 'Health checks'],
  sql: ['Relational DB'], nosql: ['Document store', 'Key-value'], cache: ['Key-value'],
  objects: ['Object storage'], warehouse: ['Columnar / warehouse'],
  search: ['Full-text search'], vector: ['Vector search', 'Full-text search'],
  queue: ['Queue', 'Dead-letter queue'], pubsub: ['Event bus', 'Dead-letter queue'],
  stream: ['Event log / stream'], streamProcessing: ['Stream processing'],
  schemaRegistry: ['Schema contract'],
  embeddings: ['Embedding model'], llm: ['LLM'], rerank: ['Rerank'],
  guardrails: ['Content safety', 'PII detection'], ocr: ['OCR'],
  secrets: ['Secrets'], config: ['Config', 'Secrets'],
  observability: ['Logs', 'Metrics', 'Alerts'], tracing: ['Traces', 'Metrics'],
  backup: ['Backup / PITR'], registry: ['OCI registry', 'Image scanning'],
  audit: ['Audit log'],
  apiGateway: ['HTTP API', 'JWT', 'WAF'], functions: ['Functions', 'Worker'],
  containers: ['Container', 'HTTP API', 'Worker'], kubernetes: ['Kubernetes', 'Container'],
  jobs: ['Scheduler', 'Worker'], orchestration: ['Workflow'],
  staticHosting: ['SPA', 'CDN'], cdn: ['CDN', 'TLS', 'WAF'],
  cicd: ['CI', 'Infrastructure as code'], gitops: ['GitOps', 'CI'], email: ['Email']
};

const BRICK_METADATA: Record<string, { features: string[]; notes: string[] }> = {
  webApp: { features: ['Present the product UI in a browser', 'Call backend APIs as a client'], notes: ['Keep the client boundary separate from the API or BFF.'] },
  mobileApp: { features: ['Present the product UI on phones and tablets', 'Call backend APIs as a mobile client'], notes: ['Store review, push certificates, and offline sync remain product decisions.'] },
  apiGateway: { features: ['Route HTTP to the right backend', 'Throttle and authenticate at the edge'], notes: ['Business rules do not belong in the gateway.'] },
  cdn: { features: ['Cache static assets close to users', 'Reduce origin load and latency'], notes: ['Cache invalidation and TTL need explicit ownership.'] },
  staticHosting: { features: ['Serve HTML, CSS, JS, and static files', 'Host a web front-end without app servers'], notes: ['SPA routing and cache headers must be configured deliberately.'] },
  identity: { features: ['Prove who the caller is', 'Issue tokens other services can validate'], notes: ['Token lifetime, MFA, and session revocation remain product policy.'] },
  functions: { features: ['Run short request-driven units of work', 'Scale managed execution for event-driven work'], notes: ['Cold starts, timeouts, and payload limits are platform-specific.'] },
  containers: { features: ['Run portable application workloads', 'Keep runtime dependencies with the workload'], notes: ['Image lifecycle and capacity remain operating responsibilities.'] },
  kubernetes: { features: ['Schedule container workloads', 'Provide service discovery and workload orchestration'], notes: ['Cluster operations are not eliminated by managed control planes.'] },
  jobs: { features: ['Run scheduled or background work', 'Separate long-running work from request paths'], notes: ['Retries and idempotency need an explicit design.'] },
  orchestration: { features: ['Coordinate multi-step workflows', 'Persist workflow progress and retries'], notes: ['Workflow state and compensation policy must be specified.'] },
  sql: { features: ['Store relational application data', 'Support transactional queries'], notes: ['Schema migrations and recovery policy remain application responsibilities.'] },
  nosql: { features: ['Store flexible or key-value records', 'Serve low-latency document access'], notes: ['Data modelling determines correctness and cost.'] },
  cache: { features: ['Cache frequently used data', 'Reduce read latency and origin load'], notes: ['Cache invalidation and source-of-truth rules must be explicit.'] },
  objects: { features: ['Store files and binary objects', 'Serve durable object data'], notes: ['Retention, access control, and lifecycle policy remain to be defined.'] },
  search: { features: ['Index content for retrieval', 'Serve full-text search queries'], notes: ['Index freshness and ranking need explicit ownership.'] },
  vector: { features: ['Store vector embeddings', 'Retrieve semantically similar content'], notes: ['Embedding model changes require re-indexing.'] },
  queue: { features: ['Buffer asynchronous work', 'Decouple producers from consumers'], notes: ['Consumers must handle retries and duplicate delivery.'] },
  pubsub: { features: ['Publish events to subscribers', 'Fan out facts without direct coupling'], notes: ['Event schemas and delivery guarantees need governance.'] },
  stream: { features: ['Transport ordered event records', 'Support replayable event processing'], notes: ['Retention and partitioning are operational choices.'] },
  llm: { features: ['Generate or transform content with a model', 'Expose model capabilities to application workflows'], notes: ['Prompt safety, cost, and evaluation are product responsibilities.'] },
  observability: { features: ['Collect service signals', 'Surface metrics, logs, and alerts'], notes: ['Signal ownership and alert response paths must be specified.'] },
  tracing: { features: ['Trace requests across service boundaries', 'Expose latency and failure paths'], notes: ['Sampling and data-retention policy need explicit ownership.'] },
  email: { features: ['Send transactional messages', 'Deliver service notifications'], notes: ['Sender reputation and delivery failures require monitoring.'] },
  cicd: { features: ['Build and test changes', 'Deliver deployable artifacts'], notes: ['Deployment approvals and rollback policy remain product decisions.'] },
  gitops: { features: ['Reconcile declared infrastructure state', 'Promote changes through version control'], notes: ['Repository access and reconciliation boundaries need governance.'] },
  waf: { features: ['Block common web attacks (injection, bots, bad IPs)', 'Apply request rules before traffic reaches apps'], notes: ['False positives can break legit clients — tune rules with observability.'] },
  loadBalancer: { features: ['Distribute traffic across healthy instances', 'Health-check backends and fail over'], notes: ['Health checks and sticky sessions must match how the app actually behaves.'] },
  warehouse: { features: ['Run analytical queries over large historical datasets', 'Separate analytics load from the operational database'], notes: ['ETL freshness and PII in analytics copies are usual compliance gaps.'] },
  streamProcessing: { features: ['Transform or aggregate streams in near real time', 'Emit derived events or write sinks continuously'], notes: ['Watermarks, late data, and state checkpoints are the hard parts.'] },
  schemaRegistry: { features: ['Version event/message schemas centrally', 'Prevent incompatible producers/consumers'], notes: ['Without enforced compatibility checks, the registry becomes documentation theater.'] },
  embeddings: { features: ['Turn text or other inputs into vectors', 'Feed vector search and RAG pipelines'], notes: ['Model and chunking choices dominate quality — brick alone is incomplete.'] },
  rerank: { features: ['Reorder retrieved candidates by relevance to a query', 'Improve RAG/search quality after a first retrieval'], notes: ['Adds latency and cost; measure lift vs plain retrieval.'] },
  guardrails: { features: ['Filter unsafe or policy-breaking model inputs/outputs', 'Reduce prompt-injection and toxic content risk'], notes: ['Rules drift; false blocks hurt UX — need monitoring and allowlists.'] },
  ocr: { features: ['Extract text from images and PDFs', 'Feed downstream search, RAG, or workflows'], notes: ['Quality varies by language, layout, and scan quality.'] },
  secrets: { features: ['Store API keys and credentials outside the repo', 'Inject secrets into runtimes at deploy/runtime'], notes: ['Rotation and least-privilege grants are usually the unfinished part.'] },
  config: { features: ['Centralize non-secret app settings by environment', 'Change flags/settings without rebuilding images when possible'], notes: ['Config vs secrets boundary is often blurred in practice.'] },
  backup: { features: ['Take recoverable copies of stateful data', 'Support restore and retention policies'], notes: ['Untested restores are a known gap — schedule restore drills.'] },
  registry: { features: ['Store versioned container (or artifact) images', 'Feed deploy pipelines with immutable artifacts'], notes: ['Image retention, scanning, and promotion between envs are often missing.'] },
  audit: { features: ['Record who did what, when, for security and compliance', 'Keep tamper-resistant operational history'], notes: ['Retention, immutability, and who can query audits are policy gaps.'] }
};

const ROLE_PHRASES: Record<string, string> = {
  webApp: 'Browser UI that presents the product to people.',
  mobileApp: 'Installable mobile client for phones and tablets.',
  apiGateway: 'Public or internal HTTP front door that routes and protects APIs.',
  cdn: 'Edge cache that serves static or cacheable content close to users.',
  staticHosting: 'Hosts static files without a custom app server.',
  identity: 'Proves who callers are and issues tokens other services trust.',
  functions: 'Runs short request- or event-driven units of work with managed scale.',
  containers: 'Runs a packaged application image with a custom runtime stack.',
  kubernetes: 'Orchestrates many containers: schedule, heal, and scale a cluster.',
  jobs: 'Runs finite batch or scheduled work to completion off the request path.',
  orchestration: 'Coordinates multi-step workflows across services with durable state.',
  sql: 'Transactional relational store for structured records.',
  nosql: 'Flexible document or key-value store for non-relational data shapes.',
  cache: 'Low-latency store for ephemeral or frequently read data.',
  objects: 'Stores large binary objects and files addressed by key.',
  search: 'Full-text or structured search index over product content.',
  vector: 'Stores embeddings for similarity search in RAG and recommendations.',
  queue: 'Buffers work between producers and consumers with at-least-once delivery.',
  pubsub: 'Fan-out event bus so many subscribers react to the same facts.',
  stream: 'Durable ordered log of events for replay and stream consumers.',
  llm: 'Generates or reasons over language for product features.',
  observability: 'Collects logs, metrics, and alerts so operators see system health.',
  tracing: 'Follows a request across services to find latency and failures.',
  email: 'Sends transactional email to users.',
  cicd: 'Builds, tests, and deploys changes through an automated pipeline.',
  gitops: 'Keeps cluster desired state in git and reconciles toward it.',
  waf: 'Request filter that blocks common web attacks before apps see traffic.',
  loadBalancer: 'Distributes traffic across instances and terminates or forwards TLS.',
  warehouse: 'Analytical store optimized for reporting and large scans, not OLTP.',
  streamProcessing: 'Transforms or aggregates event streams in near real time.',
  schemaRegistry: 'Holds shared event/API schemas and compatibility rules.',
  embeddings: 'Turns text or media into vectors for retrieval and similarity.',
  rerank: 'Reorders retrieval candidates so the best context reaches the LLM.',
  guardrails: 'Filters prompts and outputs for safety, PII, and policy.',
  ocr: 'Extracts text from images and scanned documents.',
  secrets: 'Stores and delivers credentials and keys to runtimes safely.',
  config: 'Centralizes non-secret configuration for services and feature flags.',
  backup: 'Copies and restores durable data for disaster recovery.',
  registry: 'Stores container (or package) images for deployable artifacts.',
  audit: 'Records who did what and when for security and compliance evidence.'
};


const CONCERN_TAGS: Record<string, readonly import('../document/concerns').ConcernTag[]> = {
  webApp: ['network'],
  mobileApp: ['network'],
  apiGateway: ['network', 'security'],
  cdn: ['network'],
  staticHosting: ['network'],
  identity: ['iam', 'security'],
  functions: ['ops'],
  containers: ['ops'],
  kubernetes: ['ops', 'tenancy'],
  jobs: ['ops'],
  orchestration: ['ops'],
  sql: ['data', 'dr'],
  nosql: ['data', 'dr'],
  cache: ['data'],
  objects: ['data'],
  search: ['data'],
  vector: ['data'],
  queue: ['ops', 'data'],
  pubsub: ['ops', 'data'],
  stream: ['ops', 'data'],
  llm: ['governance', 'cost'],
  observability: ['observability', 'ops'],
  tracing: ['observability'],
  email: ['ops'],
  cicd: ['ops'],
  gitops: ['ops', 'governance'],
  waf: ['security', 'network'],
  loadBalancer: ['network', 'ops'],
  warehouse: ['data', 'cost'],
  streamProcessing: ['ops', 'data'],
  schemaRegistry: ['governance', 'data'],
  embeddings: ['governance', 'cost'],
  rerank: ['governance', 'cost'],
  guardrails: ['governance', 'security'],
  ocr: ['data', 'governance'],
  secrets: ['security', 'ops'],
  config: ['ops', 'governance'],
  backup: ['dr', 'data'],
  registry: ['ops', 'security'],
  audit: ['governance', 'security']
};

const FRENCH_ROLE_PHRASES: Record<string, string> = {
  webApp: 'UI navigateur qui présente le produit aux personnes.',
  mobileApp: 'Client mobile installable pour téléphone et tablette.',
  apiGateway: 'Porte d’entrée HTTP publique ou interne qui route et protège les API.',
  cdn: 'Cache de bordure qui sert du contenu statique ou cacheable près des utilisateurs.',
  staticHosting: 'Héberge des fichiers statiques sans serveur d’application personnalisé.',
  identity: 'Prouve qui sont les appelants et émet des jetons que d’autres services font confiance.',
  functions: 'Exécute de courtes unités de travail sur requête ou événement avec scale managé.',
  containers: 'Exécute une image d’application empaquetée avec une stack runtime custom.',
  kubernetes: 'Orchestre beaucoup de conteneurs : placement, réparation et scale du cluster.',
  jobs: 'Exécute un travail batch ou planifié jusqu’au bout hors chemin requête.',
  orchestration: 'Coordonne des workflows multi-étapes entre services avec état durable.',
  sql: 'Store relationnel transactionnel pour des enregistrements structurés.',
  nosql: 'Store document ou clé-valeur flexible pour des formes de données non relationnelles.',
  cache: 'Store basse latence pour données éphémères ou lues souvent.',
  objects: 'Stocke de gros objets binaires et fichiers adressés par clé.',
  search: 'Index de recherche plein texte ou structurée sur le contenu produit.',
  vector: 'Stocke des embeddings pour recherche de similarité dans le RAG et les recommandations.',
  queue: 'Tamponne le travail entre producteurs et consommateurs avec livraison au moins une fois.',
  pubsub: 'Bus d’événements fan-out pour que plusieurs abonnés réagissent aux mêmes faits.',
  stream: 'Journal d’événements ordonné et durable pour replay et consumers.',
  llm: 'Génère ou raisonne sur du langage pour des fonctionnalités produit.',
  observability: 'Collecte logs, métriques et alertes pour voir la santé système.',
  tracing: 'Suit une requête à travers les services pour trouver latence et pannes.',
  email: 'Envoie des emails transactionnels aux utilisateurs.',
  cicd: 'Build, teste et déploie les changements via un pipeline automatisé.',
  gitops: 'Garde l’état désiré du cluster dans git et réconcilie vers lui.',
  waf: 'Filtre de requêtes qui bloque les attaques web courantes avant les apps.',
  loadBalancer: 'Répartit le trafic entre instances et termine ou relaie le TLS.',
  warehouse: 'Store analytique optimisé reporting et grands scans, pas OLTP.',
  streamProcessing: 'Transforme ou agrège des flux d’événements en quasi temps réel.',
  schemaRegistry: 'Détient les schémas d’événements/API partagés et les règles de compatibilité.',
  embeddings: 'Transforme texte ou média en vecteurs pour retrieval et similarité.',
  rerank: 'Réordonne les candidats de retrieval pour que le meilleur contexte atteigne le LLM.',
  guardrails: 'Filtre prompts et sorties pour sûreté, PII et politique.',
  ocr: 'Extrait le texte d’images et de documents scannés.',
  secrets: 'Stocke et délivre identifiants et clés aux runtimes en sécurité.',
  config: 'Centralise la configuration non secrète des services et feature flags.',
  backup: 'Copie et restaure les données durables pour la reprise après sinistre.',
  registry: 'Stocke les images conteneur (ou packages) pour artefacts déployables.',
  audit: 'Enregistre qui a fait quoi et quand pour preuves sécu et conformité.'
};

const FRENCH_BRICK_METADATA: Record<string, { features: string[]; notes: string[] }> = {
  webApp: {
    features: ['Présenter l’UI produit dans un navigateur', 'Appeler les API backend en tant que client'],
    notes: ['Garder la frontière client distincte de l’API ou du BFF.']
  },
  identity: {
    features: ['Prouver qui est l’appelant (connexion, jetons)', 'Émettre des jetons que d’autres services valident'],
    notes: ['Durée des jetons, MFA et révocation de session restent des décisions produit.']
  },
  apiGateway: {
    features: ['Router le HTTP vers le bon backend', 'Limiter le débit et authentifier à la bordure avant le code métier'],
    notes: ['Les règles métier n’appartiennent pas à la passerelle.']
  },
  mobileApp: { features: ['Présenter l’UI produit sur téléphone et tablette', 'Appeler les API backend en tant que client mobile'], notes: ['Store review, certificats push et synchronisation offline restent des décisions produit.'] },
  cdn: { features: ['Mettre les assets en cache près des utilisateurs', 'Réduire charge et latence vers l’origine'], notes: ['L’invalidation de cache et les TTL demandent un responsable explicite.'] },
  staticHosting: { features: ['Servir HTML, CSS, JS et fichiers statiques', 'Héberger le front web sans serveur d’application'], notes: ['Routage SPA et headers de cache doivent être configurés volontairement.'] },
  functions: { features: ['Exécuter de courtes unités de travail sur requête', 'Scaler une exécution managée pilotée par événements'], notes: ['Cold starts, timeouts et limites de payload sont spécifiques à la plateforme.'] },
  containers: { features: ['Exécuter des charges applicatives portables', 'Conserver les dépendances runtime avec la charge'], notes: ['Cycle de vie des images et capacité restent des responsabilités ops.'] },
  kubernetes: { features: ['Planifier les charges conteneurisées', 'Fournir découverte de services et orchestration'], notes: ['Un control plane managé n’élimine pas les opérations de cluster.'] },
  jobs: { features: ['Exécuter du travail planifié ou en arrière-plan', 'Séparer le travail long du chemin requête'], notes: ['Retries et idempotence nécessitent une conception explicite.'] },
  orchestration: { features: ['Coordonner des workflows multi-étapes', 'Persister progression et retries'], notes: ['État de workflow et politique de compensation doivent être précisés.'] },
  sql: { features: ['Stocker les données relationnelles applicatives', 'Supporter les requêtes transactionnelles'], notes: ['Migrations de schéma et reprise restent des responsabilités applicatives.'] },
  nosql: { features: ['Stocker des documents ou clés-valeurs flexibles', 'Servir un accès document à faible latence'], notes: ['La modélisation des données détermine correction et coût.'] },
  cache: { features: ['Mettre en cache les données fréquemment utilisées', 'Réduire latence de lecture et charge origine'], notes: ['Invalidation et source de vérité doivent être explicites.'] },
  objects: { features: ['Stocker fichiers et objets binaires', 'Servir des données objet durables'], notes: ['Rétention, accès et lifecycle restent à définir.'] },
  search: { features: ['Indexer le contenu pour la recherche', 'Servir les requêtes plein texte'], notes: ['Fraîcheur d’index et ranking demandent un responsable explicite.'] },
  vector: { features: ['Stocker les embeddings vectoriels', 'Retrouver du contenu sémantiquement similaire'], notes: ['Changer de modèle d’embedding impose une réindexation.'] },
  queue: { features: ['Tamponner le travail asynchrone', 'Découpler producteurs et consommateurs'], notes: ['Les consommateurs doivent gérer retries et doublons.'] },
  pubsub: { features: ['Publier des événements aux abonnés', 'Diffuser les faits sans couplage direct'], notes: ['Schémas d’événements et garanties de livraison demandent une gouvernance.'] },
  stream: { features: ['Transporter des événements ordonnés', 'Supporter le traitement rejouable'], notes: ['Rétention et partitionnement sont des choix opérationnels.'] },
  llm: { features: ['Générer ou transformer du contenu avec un modèle', 'Exposer les capacités modèle aux workflows'], notes: ['Sûreté des prompts, coût et évaluation restent produit.'] },
  observability: { features: ['Collecter les signaux des services', 'Afficher métriques, logs et alertes'], notes: ['Responsabilité des signaux et réponse aux alertes doivent être précisées.'] },
  tracing: { features: ['Tracer les requêtes entre frontières de services', 'Exposer latence et chemins d’échec'], notes: ['Sampling et rétention des données doivent être décidés.'] },
  email: { features: ['Envoyer des messages transactionnels', 'Livrer des notifications de service'], notes: ['Réputation expéditeur et échecs de livraison demandent du monitoring.'] },
  cicd: { features: ['Builder et tester les changements', 'Livrer des artefacts déployables'], notes: ['Approbations de déploiement et rollback restent des décisions produit.'] },
  gitops: { features: ['Réconcilier l’état infra déclaré', 'Promouvoir les changements via git'], notes: ['Accès dépôt et frontières de réconciliation demandent une gouvernance.'] },
  waf: { features: ['Bloquer les attaques web courantes (injection, bots, IPs)', 'Appliquer des règles avant que le trafic n’atteigne les apps'], notes: ['Les faux positifs peuvent casser des clients légitimes — régler avec de l’observabilité.'] },
  loadBalancer: { features: ['Répartir le trafic entre instances saines', 'Surveiller la santé des backends et basculer'], notes: ['Health checks et sessions sticky doivent coller au comportement réel de l’app.'] },
  warehouse: { features: ['Lancer des requêtes analytiques sur de gros historiques', 'Séparer la charge analytique de la base opérationnelle'], notes: ['Fraîcheur ETL et PII dans les copies analytiques sont des trous conformité habituels.'] },
  streamProcessing: { features: ['Transformer/agréger des flux en quasi temps réel', 'Émettre des événements dérivés ou écrire des sinks en continu'], notes: ['Watermarks, données tardives et checkpoints d’état sont le dur.'] },
  schemaRegistry: { features: ['Versionner centralement les schémas d’événements/messages', 'Éviter producteurs/consommateurs incompatibles'], notes: ['Sans contrôles de compatibilité imposés, le registry devient du théâtre documentaire.'] },
  embeddings: { features: ['Transformer texte ou autres entrées en vecteurs', 'Alimenter recherche vectorielle et pipelines RAG'], notes: ['Choix de modèle et de découpage dominent la qualité — la brique seule est incomplète.'] },
  rerank: { features: ['Réordonner les candidats récupérés selon la pertinence', 'Améliorer la qualité RAG/search après un premier retrieval'], notes: ['Ajoute latence et coût ; mesurer le gain vs retrieval simple.'] },
  guardrails: { features: ['Filtrer entrées/sorties modèle dangereuses ou hors politique', 'Réduire injection de prompts et contenu toxique'], notes: ['Les règles dérivent ; les faux blocages blessent l’UX — monitoring et allowlists.'] },
  ocr: { features: ['Extraire le texte d’images et de PDF', 'Alimenter search, RAG ou workflows en aval'], notes: ['La qualité varie selon langue, mise en page et qualité de scan.'] },
  secrets: { features: ['Stocker clés API et credentials hors du dépôt', 'Injecter les secrets dans les runtimes au deploy/runtime'], notes: ['Rotation et grants least-privilege sont souvent la partie inachevée.'] },
  config: { features: ['Centraliser les settings non secrets par environnement', 'Changer flags/settings sans rebuild d’image quand possible'], notes: ['La frontière config vs secrets est souvent floue en pratique.'] },
  backup: { features: ['Prendre des copies récupérables des données à état', 'Supporter restore et politiques de rétention'], notes: ['Restores non testés = trou connu — planifier des drills de restore.'] },
  registry: { features: ['Stocker des images de conteneurs (ou artefacts) versionnées', 'Alimenter les pipelines avec des artefacts immuables'], notes: ['Rétention d’images, scan et promotion entre envs souvent absents.'] },
  audit: { features: ['Enregistrer qui a fait quoi, quand, pour sécurité et conformité', 'Garder un historique opérationnel difficile à altérer'], notes: ['Rétention, immutabilité et qui peut requêter les audits sont des trous de politique.'] }
};

const ROLE_CAPABILITIES: Record<string, { en: string; fr: string }> = {
  webApp: { en: 'browser user interfaces', fr: 'des interfaces utilisateur web' },
  mobileApp: { en: 'mobile user interfaces', fr: 'des interfaces utilisateur mobiles' },
  apiGateway: { en: 'HTTP API routing and protection', fr: 'le routage et la protection des API HTTP' },
  cdn: { en: 'edge content delivery', fr: 'la diffusion de contenu en périphérie' },
  staticHosting: { en: 'static web content hosting', fr: 'l’hébergement de contenu web statique' },
  identity: { en: 'identity and access management', fr: 'la gestion des identités et des accès' },
  functions: { en: 'request- and event-driven execution', fr: 'l’exécution pilotée par requêtes et événements' },
  containers: { en: 'portable application execution', fr: 'l’exécution portable des applications' },
  kubernetes: { en: 'container orchestration', fr: 'l’orchestration de conteneurs' },
  jobs: { en: 'scheduled and background processing', fr: 'les traitements planifiés et en arrière-plan' },
  orchestration: { en: 'durable workflow orchestration', fr: 'l’orchestration durable des workflows' },
  sql: { en: 'transactional relational storage', fr: 'le stockage relationnel transactionnel' },
  nosql: { en: 'flexible non-relational storage', fr: 'le stockage non relationnel flexible' },
  cache: { en: 'low-latency data caching', fr: 'la mise en cache de données à faible latence' },
  objects: { en: 'durable file and object storage', fr: 'le stockage durable de fichiers et d’objets' },
  search: { en: 'full-text content retrieval', fr: 'la recherche plein texte de contenu' },
  vector: { en: 'semantic vector retrieval', fr: 'la recherche sémantique vectorielle' },
  queue: { en: 'asynchronous work buffering', fr: 'la mise en attente des traitements asynchrones' },
  pubsub: { en: 'event publication and fan-out', fr: 'la publication et la diffusion d’événements' },
  stream: { en: 'ordered event streaming', fr: 'la diffusion ordonnée de flux d’événements' },
  llm: { en: 'language model inference', fr: 'l’inférence de modèles de langage' },
  observability: { en: 'system monitoring and alerting', fr: 'la supervision et les alertes du système' },
  tracing: { en: 'distributed request tracing', fr: 'le traçage distribué des requêtes' },
  email: { en: 'transactional email delivery', fr: 'l’envoi d’e-mails transactionnels' },
  cicd: { en: 'automated build, test, and delivery', fr: 'l’automatisation du build, des tests et de la livraison' },
  gitops: { en: 'declarative infrastructure reconciliation', fr: 'la réconciliation déclarative de l’infrastructure' },
  waf: { en: 'web application firewall protection', fr: 'la protection par pare-feu applicatif web' },
  loadBalancer: { en: 'traffic distribution and TLS termination', fr: 'la répartition de trafic et la terminaison TLS' },
  warehouse: { en: 'analytical data warehousing', fr: 'l’entrepôt de données analytique' },
  streamProcessing: { en: 'real-time stream transformation', fr: 'la transformation de flux en temps réel' },
  schemaRegistry: { en: 'centralized schema governance', fr: 'la gouvernance centralisée des schémas' },
  embeddings: { en: 'vector embedding generation', fr: 'la génération d’embeddings vectoriels' },
  rerank: { en: 'retrieval result reranking', fr: 'le reranking des résultats de retrieval' },
  guardrails: { en: 'AI safety and policy filtering', fr: 'le filtrage de sûreté et de politique IA' },
  ocr: { en: 'optical character recognition', fr: 'la reconnaissance optique de caractères' },
  secrets: { en: 'secure credential storage and delivery', fr: 'le stockage et la délivrance sécurisés de credentials' },
  config: { en: 'centralized configuration management', fr: 'la gestion centralisée de configuration' },
  backup: { en: 'durable data backup and restore', fr: 'la sauvegarde et la restauration de données durables' },
  registry: { en: 'container image registry', fr: 'le registre d’images conteneur' },
  audit: { en: 'security and compliance audit logging', fr: 'la journalisation d’audit sécurité et conformité' }
};

const TECHNOLOGY_DESCRIPTIONS: Record<string, { en: string; fr: string }> = {
  react: { en: 'React builds interactive browser interfaces from reusable components.', fr: 'React construit des interfaces navigateur interactives à partir de composants réutilisables.' },
  typescript: { en: 'TypeScript adds static types to JavaScript for safer application code.', fr: 'TypeScript ajoute des types statiques à JavaScript pour un code applicatif plus sûr.' },
  'next.js': { en: 'Next.js is a React framework for production web applications.', fr: 'Next.js est un framework React pour les applications web de production.' },
  'node.js': { en: 'Node.js runs JavaScript services and tooling outside the browser.', fr: 'Node.js exécute des services et outils JavaScript hors du navigateur.' },
  postgresql: { en: 'PostgreSQL is a transactional relational database.', fr: 'PostgreSQL est une base de données relationnelle transactionnelle.' },
  redis: { en: 'Redis provides low-latency in-memory data storage and caching.', fr: 'Redis fournit du stockage de données en mémoire et du cache à faible latence.' },
  'openai api': { en: 'OpenAI API provides hosted language-model inference.', fr: 'OpenAI API fournit de l’inférence de modèles de langage hébergée.' },
  'firebase auth': { en: 'Firebase Auth provides managed user authentication.', fr: 'Firebase Auth fournit une authentification utilisateur managée.' },
  'supabase auth': { en: 'Supabase Auth provides authentication backed by Supabase.', fr: 'Supabase Auth fournit une authentification adossée à Supabase.' },
  'http api': { en: 'HTTP API exposes application capabilities over HTTP.', fr: 'HTTP API expose les capacités applicatives sur HTTP.' },
  jwt: { en: 'JWT carries signed claims between authenticated parties.', fr: 'JWT transporte des claims signés entre parties authentifiées.' },
  oidc: { en: 'OIDC standardizes identity verification on top of OAuth.', fr: 'OIDC standardise la vérification d’identité au-dessus d’OAuth.' },
  'relational db': { en: 'Relational DB stores structured data with transactions and queries.', fr: 'Relational DB stocke des données structurées avec transactions et requêtes.' },
  'document store': { en: 'Document store persists flexible document-shaped records.', fr: 'Document store persiste des enregistrements flexibles au format document.' },
  'key-value': { en: 'Key-value stores retrieve values efficiently by key.', fr: 'Key-value récupère efficacement les valeurs par clé.' },
  'object storage': { en: 'Object storage keeps durable files and binary objects.', fr: 'Object storage conserve durablement fichiers et objets binaires.' },
  queue: { en: 'Queue buffers asynchronous work between producers and consumers.', fr: 'Queue met en attente le travail asynchrone entre producteurs et consommateurs.' },
  'event bus': { en: 'Event bus distributes events to independent subscribers.', fr: 'Event bus diffuse des événements à des abonnés indépendants.' },
  llm: { en: 'LLM provides language-model inference for application features.', fr: 'LLM fournit l’inférence de modèle de langage pour les fonctionnalités applicatives.' }
};

const DEPENDENCIES: readonly LegoDependencySuggestion[] = [
  { from: 'webApp', to: 'identity', strength: 'required', why_en: 'People need to sign in before using the product.', why_fr: 'Les gens doivent se connecter avant d’utiliser le produit.', protocol_id: 'oidc', kind: 'sync' },
  { from: 'webApp', to: 'apiGateway', strength: 'recommended', why_en: 'The browser should call a single API entry, not every backend directly.', why_fr: 'Le navigateur devrait appeler une seule entrée API, pas chaque backend.', protocol_id: 'rest', kind: 'sync' },
  { from: 'webApp', to: 'cdn', strength: 'optional', why_en: 'Static assets and edge caching keep the UI fast.', why_fr: 'Les assets et le cache edge gardent l’UI rapide.', protocol_id: 'rest', kind: 'sync' },
  { from: 'mobileApp', to: 'identity', strength: 'required', why_en: 'The app needs a login / token issuer.', why_fr: 'L’app a besoin d’un login / émetteur de jetons.', protocol_id: 'oidc', kind: 'sync' },
  { from: 'mobileApp', to: 'apiGateway', strength: 'recommended', why_en: 'Mobile clients should hit one API front door.', why_fr: 'Les clients mobiles devraient passer par une seule porte API.', protocol_id: 'rest', kind: 'sync' },
  { from: 'apiGateway', to: 'identity', strength: 'recommended', why_en: 'The gateway often validates tokens before routing.', why_fr: 'La passerelle valide souvent les jetons avant de router.', protocol_id: 'oidc', kind: 'sync' },
  { from: 'cdn', to: 'staticHosting', strength: 'recommended', why_en: 'CDN usually fronts the files or app shell you publish.', why_fr: 'Le CDN sert en général les fichiers / shell que tu publies.', protocol_id: 'rest', kind: 'sync' },
  { from: 'staticHosting', to: 'cdn', strength: 'optional', why_en: 'A CDN in front of static hosting is the usual production shape.', why_fr: 'Un CDN devant l’hébergement statique est la forme prod habituelle.', protocol_id: 'rest', kind: 'sync' },
  { from: 'waf', to: 'apiGateway', strength: 'recommended', why_en: 'WAF sits in front of the public entry you protect.', why_fr: 'Le WAF se place devant l’entrée publique à protéger.', protocol_id: 'rest', kind: 'sync' },
  { from: 'loadBalancer', to: 'containers', strength: 'recommended', why_en: 'The load balancer spreads traffic across running instances.', why_fr: 'Le load balancer répartit le trafic entre les instances.', protocol_id: 'rest', kind: 'sync' },
  { from: 'identity', to: 'secrets', strength: 'recommended', why_en: 'Auth providers need private keys and client secrets stored safely.', why_fr: 'L’auth a besoin de clés et secrets stockés proprement.', protocol_id: 'rest', kind: 'sync' },
  { from: 'functions', to: 'secrets', strength: 'required', why_en: 'Serverless code needs credentials without hard-coding them.', why_fr: 'Le code serverless a besoin de credentials sans les coder en dur.', protocol_id: 'rest', kind: 'sync' },
  { from: 'functions', to: 'sql', strength: 'recommended', why_en: 'Most backends persist business data in a database.', why_fr: 'La plupart des backends stockent les données métier en base.', protocol_id: 'sql', kind: 'sync' },
  { from: 'containers', to: 'secrets', strength: 'required', why_en: 'Containers need runtime secrets and config injection.', why_fr: 'Les conteneurs ont besoin de secrets et de config au runtime.', protocol_id: 'rest', kind: 'sync' },
  { from: 'containers', to: 'registry', strength: 'recommended', why_en: 'Images have to come from a container registry.', why_fr: 'Les images doivent venir d’un registry.', protocol_id: 'rest', kind: 'sync' },
  { from: 'kubernetes', to: 'observability', strength: 'recommended', why_en: 'Clusters are hard to operate without metrics and logs.', why_fr: 'Un cluster sans métriques / logs est difficile à opérer.', protocol_id: 'rest', kind: 'sync' },
  { from: 'jobs', to: 'queue', strength: 'recommended', why_en: 'Background work usually waits on a queue or schedule trigger.', why_fr: 'Le travail de fond attend en général une file ou un schedule.', protocol_id: 'queue', kind: 'async' },
  { from: 'orchestration', to: 'queue', strength: 'recommended', why_en: 'Workflows coordinate steps through queues or events.', why_fr: 'Les workflows coordonnent les étapes via files ou events.', protocol_id: 'queue', kind: 'async' },
  { from: 'sql', to: 'secrets', strength: 'required', why_en: 'Databases need connection credentials.', why_fr: 'Les bases ont besoin d’identifiants de connexion.', protocol_id: 'rest', kind: 'sync' },
  { from: 'sql', to: 'backup', strength: 'recommended', why_en: 'Durable data needs a backup path.', why_fr: 'Des données durables ont besoin de sauvegarde.', protocol_id: 'rest', kind: 'sync' },
  { from: 'nosql', to: 'secrets', strength: 'required', why_en: 'Document stores need access credentials.', why_fr: 'Les stores document ont besoin d’accès.', protocol_id: 'rest', kind: 'sync' },
  { from: 'cache', to: 'sql', strength: 'optional', why_en: 'Cache often sits in front of a primary database.', why_fr: 'Le cache se place souvent devant une base primaire.', protocol_id: 'sql', kind: 'sync' },
  { from: 'objects', to: 'secrets', strength: 'recommended', why_en: 'Object storage needs access keys / IAM roles.', why_fr: 'Le stockage objet a besoin de clés / rôles.', protocol_id: 'rest', kind: 'sync' },
  { from: 'search', to: 'objects', strength: 'optional', why_en: 'Search indexes are often built from documents in object storage.', why_fr: 'Les index sont souvent construits depuis des docs en object storage.', protocol_id: 'object', kind: 'sync' },
  { from: 'vector', to: 'embeddings', strength: 'required', why_en: 'Vectors come from an embedding model.', why_fr: 'Les vecteurs viennent d’un modèle d’embeddings.', protocol_id: 'rest', kind: 'sync' },
  { from: 'queue', to: 'functions', strength: 'recommended', why_en: 'Something must consume the messages.', why_fr: 'Quelque chose doit consommer les messages.', protocol_id: 'queue', kind: 'async' },
  { from: 'pubsub', to: 'functions', strength: 'recommended', why_en: 'Subscribers process published events.', why_fr: 'Des subscribers traitent les events publiés.', protocol_id: 'pubsub', kind: 'async' },
  { from: 'stream', to: 'streamProcessing', strength: 'recommended', why_en: 'Streams usually feed a processor or consumer service.', why_fr: 'Les streams alimentent en général un processeur.', protocol_id: 'kafka', kind: 'async' },
  { from: 'llm', to: 'guardrails', strength: 'recommended', why_en: 'LLM answers should pass safety / policy checks.', why_fr: 'Les réponses LLM devraient passer des garde-fous.', protocol_id: 'rest', kind: 'sync' },
  { from: 'llm', to: 'secrets', strength: 'required', why_en: 'Model APIs need API keys.', why_fr: 'Les APIs de modèles ont besoin de clés.', protocol_id: 'rest', kind: 'sync' },
  { from: 'embeddings', to: 'vector', strength: 'recommended', why_en: 'Embeddings are stored in a vector index.', why_fr: 'Les embeddings sont stockés dans un index vectoriel.', protocol_id: 'rest', kind: 'sync' },
  { from: 'email', to: 'secrets', strength: 'recommended', why_en: 'Mail providers need SMTP / API credentials.', why_fr: 'Les providers mail ont besoin de credentials.', protocol_id: 'smtp', kind: 'async' },
  { from: 'observability', to: 'secrets', strength: 'optional', why_en: 'Agents and exporters need sink credentials.', why_fr: 'Agents / exporters ont besoin d’accès au sink.', protocol_id: 'rest', kind: 'sync' },
  { from: 'cicd', to: 'registry', strength: 'recommended', why_en: 'Pipelines publish build artifacts / images.', why_fr: 'Les pipelines publient artefacts / images.', protocol_id: 'rest', kind: 'sync' },
  { from: 'gitops', to: 'kubernetes', strength: 'recommended', why_en: 'GitOps applies desired state to a cluster.', why_fr: 'GitOps applique l’état désiré sur un cluster.', protocol_id: 'rest', kind: 'sync' },
  { from: 'audit', to: 'objects', strength: 'optional', why_en: 'Audit trails are often archived to object storage.', why_fr: 'Les pistes d’audit partent souvent en object storage.', protocol_id: 'object', kind: 'sync' }
];

export const CATALOG_SEED = { intents: INTENTS, variants: VARIANTS, scopes: LOCKED_SCOPES, scopeAliases: SCOPE_ALIASES, roleScopes: ROLE_SCOPES, icons: ICONS, layers: LAYERS, defaultScopes: SCOPES, capabilities: CAPABILITIES, brickMetadata: BRICK_METADATA, frenchBrickMetadata: FRENCH_BRICK_METADATA, rolePhrases: ROLE_PHRASES, frenchRolePhrases: FRENCH_ROLE_PHRASES, concernTags: CONCERN_TAGS, roleCapabilities: ROLE_CAPABILITIES, technologyDescriptions: TECHNOLOGY_DESCRIPTIONS, dependencies: DEPENDENCIES } as const;

export function buildCatalogSnapshot(lang: LegoLanguage = 'en'): LegoCatalogSnapshot {
  const metadata = lang === 'fr' ? CATALOG_SEED.frenchBrickMetadata : CATALOG_SEED.brickMetadata;
  const phrases = lang === 'fr' ? CATALOG_SEED.frenchRolePhrases : CATALOG_SEED.rolePhrases;
  const bricks = Object.fromEntries(Object.keys(CATALOG_SEED.icons).map(id => [id, {
    id,
    icon: CATALOG_SEED.icons[id] || 'box',
    layer: CATALOG_SEED.layers[id] || 'services',
    defaultScope: CATALOG_SEED.defaultScopes[id] || 'product',
    capabilities: [...(CATALOG_SEED.capabilities[id] || [])],
    role: phrases[id] || id,
    purpose: phrases[id] || id,
    concernTags: [...(CATALOG_SEED.concernTags[id] || [])],
    responsibilities: [...(metadata[id]?.features || [])],
    notes: [...(metadata[id]?.notes || [])],
    affinities: [...(CATALOG_SEED.roleScopes[id] || [])],
    capabilityPhrase: CATALOG_SEED.roleCapabilities[id]?.[lang] || ''
  }]));
  return {
    version: 'seed',
    lang,
    scopes: CATALOG_SEED.scopes.map(([id, en, fr]) => ({ id, label: lang === 'fr' ? fr : en })),
    aliases: { ...CATALOG_SEED.scopeAliases },
    bricks,
    intents: CATALOG_SEED.intents.map(intent => ({ ...intent, modes: [...intent.modes], shapes: intent.shapes && [...intent.shapes] })),
    variants: CATALOG_SEED.variants.map(variant => ({ ...variant })),
    dependencies: CATALOG_SEED.dependencies.map(dependency => ({ ...dependency })),
    technologyDescriptions: Object.fromEntries(Object.entries(CATALOG_SEED.technologyDescriptions).map(([key, value]) => [key, value[lang]]))
  };
}
